apiVersion: apps/v1
kind: Deployment
metadata:
  name: jidalli-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jidalli
  template:
    metadata:
      labels:
        app: jidalli
    spec:
      containers:
        - name: jidalli
          image: petbell/jidalli:v1
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              value: "sqlite:///./jidalli.db"
