apiVersion: v1
kind: Service
metadata:
  name: jidalli-service
spec:
  selector:
    app: jidalli
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30303
  type: NodePort
  
